### PR TITLE
Fix normalization issue.

### LINKED ISSUE #4: Problem with paths with ..
This is the cause of https://github.com/broccolijs/broccoli-funnel/issues/81, more details there. I'll try to add a failing test and maybe even a fix.

### PR DESCRIPTION
**Pull request by nathanhammond**
Closes #4.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ function existsSync(filepath, parent){
     stats = lstatSync(resolvedPath);
     // if symlink, check if target
     if (stats && stats.isSymbolicLink()) {
-      link         = readlinkSync(resolvedPath);
+      link         = path.normalize(readlinkSync(resolvedPath));
```
Comment (MiguelMadero) [inline index.js:15]: argh! it was this simple... Thanks for fixing this
